// ============================================================
//  F1 Manager — data.js
//  Données statiques : circuits, équipes, pilotes, pneus
// ============================================================

const F1Data = {

  // ── PNEUS ─────────────────────────────────────────────────
  tyres: {
    SOFT:   { name: 'Soft',     color: '#FF3333', degradationRate: 0.045, grip: 1.00, warmupLaps: 1 },
    MEDIUM: { name: 'Medium',   color: '#FFD700', degradationRate: 0.025, grip: 0.97, warmupLaps: 2 },
    HARD:   { name: 'Hard',     color: '#FFFFFF', degradationRate: 0.012, grip: 0.94, warmupLaps: 3 },
    INTER:  { name: 'Inter',    color: '#00CC44', degradationRate: 0.030, grip: 0.88, warmupLaps: 2 },
    WET:    { name: 'Full Wet', color: '#4488FF', degradationRate: 0.020, grip: 0.80, warmupLaps: 2 },
  },

  // ── CIRCUITS ──────────────────────────────────────────────
  circuits: [
    {
      id: 'bahrain',
      name: 'Bahrain',
      fullName: 'Bahrain International Circuit',
      laps: 57,
      lapDistance: 5.412, // km
      baseLapTime: 93.5,  // secondes
      pitLoss: 22,        // secondes perdues au pit stop
      overtakingDifficulty: 0.4, // 0=facile, 1=difficile
      tyreDegradation: 1.2,      // multiplicateur dégradation
      drsZones: 2,
      fuelPerLap: 1.8,           // kg/tour
    },
    {
      id: 'monaco',
      name: 'Monaco',
      fullName: 'Circuit de Monaco',
      laps: 78,
      lapDistance: 3.337,
      baseLapTime: 75.0,
      pitLoss: 28,
      overtakingDifficulty: 0.95,
      tyreDegradation: 0.7,
      drsZones: 1,
      fuelPerLap: 1.2,
    },
    {
      id: 'silverstone',
      name: 'Silverstone',
      fullName: 'Silverstone Circuit',
      laps: 52,
      lapDistance: 5.891,
      baseLapTime: 89.5,
      pitLoss: 21,
      overtakingDifficulty: 0.45,
      tyreDegradation: 1.4,
      drsZones: 2,
      fuelPerLap: 2.0,
    },
    {
      id: 'monza',
      name: 'Monza',
      fullName: 'Autodromo Nazionale Monza',
      laps: 53,
      lapDistance: 5.793,
      baseLapTime: 82.5,
      pitLoss: 23,
      overtakingDifficulty: 0.3,
      tyreDegradation: 0.9,
      drsZones: 2,
      fuelPerLap: 1.9,
    },
    {
      id: 'spa',
      name: 'Spa',
      fullName: 'Circuit de Spa-Francorchamps',
      laps: 44,
      lapDistance: 7.004,
      baseLapTime: 106.0,
      pitLoss: 24,
      overtakingDifficulty: 0.35,
      tyreDegradation: 1.1,
      drsZones: 2,
      fuelPerLap: 2.2,
    },
    {
      id: 'suzuka',
      name: 'Suzuka',
      fullName: 'Suzuka International Racing Course',
      laps: 53,
      lapDistance: 5.807,
      baseLapTime: 91.0,
      pitLoss: 22,
      overtakingDifficulty: 0.6,
      tyreDegradation: 1.15,
      drsZones: 1,
      fuelPerLap: 1.9,
    },
  ],

  // ── ÉQUIPES ───────────────────────────────────────────────
  teams: [
    {
      id: 'redbull',
      name: 'Red Bull Racing',
      shortName: 'RBR',
      color: '#1E3A6E',
      accentColor: '#FFD700',
      budget: 500,        // millions €
      performance: 95,    // 0-100
      reliability: 88,
      aero: 96,
      chassis: 94,
      engine: 93,
      isPlayer: false,
    },
    {
      id: 'ferrari',
      name: 'Ferrari',
      shortName: 'FER',
      color: '#CC0000',
      accentColor: '#FFD700',
      budget: 480,
      performance: 92,
      reliability: 84,
      aero: 91,
      chassis: 92,
      engine: 95,
      isPlayer: false,
    },
    {
      id: 'mercedes',
      name: 'Mercedes',
      shortName: 'MER',
      color: '#00D2BE',
      accentColor: '#FFFFFF',
      budget: 490,
      performance: 90,
      reliability: 90,
      aero: 89,
      chassis: 93,
      engine: 96,
      isPlayer: false,
    },
    {
      id: 'mclaren',
      name: 'McLaren',
      shortName: 'MCL',
      color: '#FF8000',
      accentColor: '#FFFFFF',
      budget: 420,
      performance: 88,
      reliability: 85,
      aero: 90,
      chassis: 87,
      engine: 90,
      isPlayer: false,
    },
    {
      id: 'aston',
      name: 'Aston Martin',
      shortName: 'AMR',
      color: '#006F62',
      accentColor: '#FFD700',
      budget: 380,
      performance: 82,
      reliability: 83,
      aero: 81,
      chassis: 83,
      engine: 88,
      isPlayer: false,
    },
    {
      id: 'alpine',
      name: 'Alpine',
      shortName: 'ALP',
      color: '#0090FF',
      accentColor: '#FF0000',
      budget: 320,
      performance: 75,
      reliability: 78,
      aero: 76,
      chassis: 74,
      engine: 82,
      isPlayer: false,
    },
    {
      id: 'williams',
      name: 'Williams',
      shortName: 'WIL',
      color: '#005AFF',
      accentColor: '#FFFFFF',
      budget: 200,
      performance: 65,
      reliability: 75,
      aero: 64,
      chassis: 66,
      engine: 85,
      isPlayer: false,
    },
    {
      id: 'haas',
      name: 'Haas',
      shortName: 'HAA',
      color: '#FFFFFF',
      accentColor: '#FF0000',
      budget: 180,
      performance: 62,
      reliability: 72,
      aero: 61,
      chassis: 63,
      engine: 85,
      isPlayer: false,
    },
    {
      id: 'sauber',
      name: 'Kick Sauber',
      shortName: 'SAU',
      color: '#00E701',
      accentColor: '#FFFFFF',
      budget: 190,
      performance: 60,
      reliability: 73,
      aero: 59,
      chassis: 61,
      engine: 84,
      isPlayer: false,
    },
    {
      id: 'racingbulls',
      name: 'Racing Bulls',
      shortName: 'RCB',
      color: '#4477FF',
      accentColor: '#FFD700',
      budget: 210,
      performance: 68,
      reliability: 76,
      aero: 67,
      chassis: 69,
      engine: 85,
      isPlayer: false,
    },
  ],

  // ── PILOTES ───────────────────────────────────────────────
  drivers: [
    { id: 'VER', name: 'Verstappen', firstName: 'Max',       teamId: 'redbull',     number: 1,  pace: 97, consistency: 95, wetSkill: 96, overtaking: 94, defending: 92, salary: 55 },
    { id: 'PER', name: 'Pérez',      firstName: 'Sergio',    teamId: 'redbull',     number: 11, pace: 87, consistency: 82, wetSkill: 80, overtaking: 83, defending: 85, salary: 12 },
    { id: 'LEC', name: 'Leclerc',    firstName: 'Charles',   teamId: 'ferrari',     number: 16, pace: 93, consistency: 86, wetSkill: 91, overtaking: 88, defending: 84, salary: 25 },
    { id: 'SAI', name: 'Sainz',      firstName: 'Carlos',    teamId: 'ferrari',     number: 55, pace: 89, consistency: 90, wetSkill: 85, overtaking: 85, defending: 87, salary: 10 },
    { id: 'HAM', name: 'Hamilton',   firstName: 'Lewis',     teamId: 'mercedes',    number: 44, pace: 94, consistency: 92, wetSkill: 95, overtaking: 93, defending: 91, salary: 40 },
    { id: 'RUS', name: 'Russell',    firstName: 'George',    teamId: 'mercedes',    number: 63, pace: 90, consistency: 88, wetSkill: 87, overtaking: 87, defending: 83, salary: 8  },
    { id: 'NOR', name: 'Norris',     firstName: 'Lando',     teamId: 'mclaren',     number: 4,  pace: 92, consistency: 87, wetSkill: 88, overtaking: 89, defending: 82, salary: 15 },
    { id: 'PIA', name: 'Piastri',    firstName: 'Oscar',     teamId: 'mclaren',     number: 81, pace: 88, consistency: 85, wetSkill: 83, overtaking: 84, defending: 80, salary: 6  },
    { id: 'ALO', name: 'Alonso',     firstName: 'Fernando',  teamId: 'aston',       number: 14, pace: 91, consistency: 89, wetSkill: 93, overtaking: 90, defending: 95, salary: 20 },
    { id: 'STR', name: 'Stroll',     firstName: 'Lance',     teamId: 'aston',       number: 18, pace: 78, consistency: 75, wetSkill: 73, overtaking: 74, defending: 76, salary: 8  },
    { id: 'GAS', name: 'Gasly',      firstName: 'Pierre',    teamId: 'alpine',      number: 10, pace: 83, consistency: 81, wetSkill: 82, overtaking: 80, defending: 79, salary: 5  },
    { id: 'OCO', name: 'Ocon',       firstName: 'Esteban',   teamId: 'alpine',      number: 31, pace: 80, consistency: 79, wetSkill: 78, overtaking: 77, defending: 78, salary: 4  },
    { id: 'ALB', name: 'Albon',      firstName: 'Alexander', teamId: 'williams',    number: 23, pace: 81, consistency: 80, wetSkill: 79, overtaking: 79, defending: 77, salary: 3  },
    { id: 'SAR', name: 'Sargeant',   firstName: 'Logan',     teamId: 'williams',    number: 2,  pace: 72, consistency: 70, wetSkill: 68, overtaking: 69, defending: 71, salary: 1  },
    { id: 'HUL', name: 'Hülkenberg', firstName: 'Nico',      teamId: 'haas',        number: 27, pace: 82, consistency: 83, wetSkill: 80, overtaking: 78, defending: 80, salary: 3  },
    { id: 'MAG', name: 'Magnussen',  firstName: 'Kevin',     teamId: 'haas',        number: 20, pace: 77, consistency: 74, wetSkill: 76, overtaking: 75, defending: 77, salary: 2  },
    { id: 'BOT', name: 'Bottas',     firstName: 'Valtteri',  teamId: 'sauber',      number: 77, pace: 82, consistency: 81, wetSkill: 80, overtaking: 78, defending: 79, salary: 4  },
    { id: 'ZHO', name: 'Zhou',       firstName: 'Guanyu',    teamId: 'sauber',      number: 24, pace: 75, consistency: 74, wetSkill: 72, overtaking: 72, defending: 73, salary: 2  },
    { id: 'TSU', name: 'Tsunoda',    firstName: 'Yuki',      teamId: 'racingbulls', number: 22, pace: 83, consistency: 78, wetSkill: 79, overtaking: 81, defending: 75, salary: 3  },
    { id: 'RIC', name: 'Ricciardo',  firstName: 'Daniel',    teamId: 'racingbulls', number: 3,  pace: 84, consistency: 79, wetSkill: 81, overtaking: 86, defending: 78, salary: 5  },
  ],

  // ── POINTS F1 ─────────────────────────────────────────────
  pointsSystem: [25, 18, 15, 12, 10, 8, 6, 4, 2, 1],

};
